{
  "info": {
    "author": "Bright Interactive",
    "author_email": "francis@bright-interactive.co.uk",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "",
    "description_content_type": "",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "http://github.com/brightinteractive/django-raise-exception-view/",
    "keywords": "",
    "license": "BSD",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-raise-exception-view",
    "package_url": "https://pypi.org/project/django-raise-exception-view/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-raise-exception-view/",
    "project_urls": {
      "Homepage": "http://github.com/brightinteractive/django-raise-exception-view/"
    },
    "release_url": "https://pypi.org/project/django-raise-exception-view/1.0.2/",
    "requires_dist": null,
    "requires_python": "",
    "summary": "Django view that raises an exception so you can test your logging setup",
    "version": "1.0.2",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 7722091,
  "releases": {
    "1.0.0": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "61d32c9d0e2ee9c22bd60aad9a5624d02e9bbd941bd384c7630adc2353707307",
          "md5": "a586010707d43857919ce4dd2c56588c",
          "sha256": "83bff46d513fc1e297198982ee9747b27f2968ad035f5042673138662351bfe2"
        },
        "downloads": -1,
        "filename": "django-raise-exception-view-1.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "a586010707d43857919ce4dd2c56588c",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 2073,
        "upload_time": "2012-04-13T12:23:46",
        "upload_time_iso_8601": "2012-04-13T12:23:46.101908Z",
        "url": "https://files.pythonhosted.org/packages/61/d3/2c9d0e2ee9c22bd60aad9a5624d02e9bbd941bd384c7630adc2353707307/django-raise-exception-view-1.0.0.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ],
    "1.0.1": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "1cea0c67c37ab96887b8e9d933f27100c95aa34bce3ae611104b6faf48f40d96",
          "md5": "88e2eb0202a60f790c00cf1986feaa8f",
          "sha256": "63dff4c5a8209a4be0139e82478d6dc2b9197c641f34047fb9d9d68bcfca344b"
        },
        "downloads": -1,
        "filename": "django-raise-exception-view-1.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "88e2eb0202a60f790c00cf1986feaa8f",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 2077,
        "upload_time": "2012-04-13T12:27:48",
        "upload_time_iso_8601": "2012-04-13T12:27:48.320501Z",
        "url": "https://files.pythonhosted.org/packages/1c/ea/0c67c37ab96887b8e9d933f27100c95aa34bce3ae611104b6faf48f40d96/django-raise-exception-view-1.0.1.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ],
    "1.0.2": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "16bd0b9ffaab721add42dac19e6aef683b7d0c63c5478aed8085053fd6e888ce",
          "md5": "3b217cb343f7ed4d7d26b7cdbafe669f",
          "sha256": "462cacd3e40b8f17cf5ad0b3c135522711e52ea1b1fcf1f437afda1bcc02dfc8"
        },
        "downloads": -1,
        "filename": "django-raise-exception-view-1.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "3b217cb343f7ed4d7d26b7cdbafe669f",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": null,
        "size": 4785,
        "upload_time": "2020-07-17T13:17:50",
        "upload_time_iso_8601": "2020-07-17T13:17:50.491375Z",
        "url": "https://files.pythonhosted.org/packages/16/bd/0b9ffaab721add42dac19e6aef683b7d0c63c5478aed8085053fd6e888ce/django-raise-exception-view-1.0.2.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "16bd0b9ffaab721add42dac19e6aef683b7d0c63c5478aed8085053fd6e888ce",
        "md5": "3b217cb343f7ed4d7d26b7cdbafe669f",
        "sha256": "462cacd3e40b8f17cf5ad0b3c135522711e52ea1b1fcf1f437afda1bcc02dfc8"
      },
      "downloads": -1,
      "filename": "django-raise-exception-view-1.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "3b217cb343f7ed4d7d26b7cdbafe669f",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 4785,
      "upload_time": "2020-07-17T13:17:50",
      "upload_time_iso_8601": "2020-07-17T13:17:50.491375Z",
      "url": "https://files.pythonhosted.org/packages/16/bd/0b9ffaab721add42dac19e6aef683b7d0c63c5478aed8085053fd6e888ce/django-raise-exception-view-1.0.2.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}