{
  "info": {
    "author": "Fernando Celmer",
    "author_email": "email@fernandocelmer.com",
    "bugtrack_url": null,
    "classifiers": [
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Natural Language :: English",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7",
      "Programming Language :: Python :: 3.8",
      "Programming Language :: Python :: 3.9"
    ],
    "description": "# upy-error\n\n![PyPI - Python Version](https://img.shields.io/pypi/pyversions/upy-error)\n![PyPI](https://img.shields.io/pypi/v/upy-error)\n![GitHub last commit](https://img.shields.io/github/last-commit/UpyExplorer/upy-error)\n![GitHub followers](https://img.shields.io/github/followers/UpyExplorer?label=UpyExplorer&style=social)\n<br>\n\n## How to install?\n```python\n\npip install upy-error\n\n```\n## How to use?\n```python\n# Import the package\nfrom upy_error import format_exception\n```\n### Exception example with (log)\n```python\ntry:\n    print(x)\nexcept Exception as error:\n    # Using the function to process the error with the 'logging' package.\n    format_exception(error=error, log=True)\n```\n**Output:**\n```shell\n==========================================\n2022-07-23 00:13:37,577 ERROR \nUpyError: \n  File \"test_upy_error.py\", line 4, in <module>\n    print(x)\nNameError: name 'x' is not defined\n==========================================\n```\n\n### Exception example with (print)\n```python\ntry:\n    1 / 0\nexcept Exception as error:\n    # Using the function to return the error in string format.\n    print(format_exception(error=error))\n```\n**Output:**\n```shell\nUpyError: \n  File \"test_upy_error.py\", line 11, in <module>\n    1 / 0\nZeroDivisionError: division by zero\n```\n\n<!-- LICENSE -->\n## License\n\nDistributed under the MIT License. See `LICENSE` for more information.\n\n<!-- CONTACT -->\n## Contact\n\nFernando Celmer - email@fernandocelmer.com\n\n- Project Github: [https://github.com/UpyExplorer/upy-error](https://github.com/UpyExplorer/upy-error)\n- Project Pypi: [https://pypi.org/project/upy-error/](https://pypi.org/project/upy-error/)\n",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/UpyExplorer/upy-error",
    "keywords": "",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "upy-error",
    "package_url": "https://pypi.org/project/upy-error/",
    "platform": null,
    "project_url": "https://pypi.org/project/upy-error/",
    "project_urls": {
      "Homepage": "https://github.com/UpyExplorer/upy-error"
    },
    "release_url": "https://pypi.org/project/upy-error/0.0.2/",
    "requires_dist": null,
    "requires_python": ">=3.6",
    "summary": "Python Trace Error",
    "version": "0.0.2",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 14522395,
  "releases": {
    "0.0.1": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "e20400d40500da9470131aeff569716c3be3d5a2f8c0b5a8c5eea6b7332d7fde",
          "md5": "01bbe9d1fa1b82edbaf90abd87616423",
          "sha256": "8ce1c4d6b83e16167bf6c803053054cc264b8994f21d6fca37d16ef9c3d48df5"
        },
        "downloads": -1,
        "filename": "upy_error-0.0.1-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "01bbe9d1fa1b82edbaf90abd87616423",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "requires_python": ">=3.6",
        "size": 2188,
        "upload_time": "2022-01-15T21:35:53",
        "upload_time_iso_8601": "2022-01-15T21:35:53.958912Z",
        "url": "https://files.pythonhosted.org/packages/e2/04/00d40500da9470131aeff569716c3be3d5a2f8c0b5a8c5eea6b7332d7fde/upy_error-0.0.1-py2.py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "523a9fca8d8fd262fe576956a3c8024f5b4ea102ce63eb31f75fea5fa7f78954",
          "md5": "01d5f897988891239dbe6d48badb6ab7",
          "sha256": "609dfc46bfd410adbdcdfd5966633bfb8b9bc2b012df549f94ba75f9fce78fde"
        },
        "downloads": -1,
        "filename": "upy-error-0.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "01d5f897988891239dbe6d48badb6ab7",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": ">=3.6",
        "size": 2072,
        "upload_time": "2022-01-15T21:35:55",
        "upload_time_iso_8601": "2022-01-15T21:35:55.743895Z",
        "url": "https://files.pythonhosted.org/packages/52/3a/9fca8d8fd262fe576956a3c8024f5b4ea102ce63eb31f75fea5fa7f78954/upy-error-0.0.1.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ],
    "0.0.2": [
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "abc46abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b",
          "md5": "826adedaba1b854941e70d7f80892677",
          "sha256": "42ce128f084f6f6a02f53a19fc86ff8b2fc9b61f379f7343b16e7235d65916c2"
        },
        "downloads": -1,
        "filename": "upy_error-0.0.2-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "826adedaba1b854941e70d7f80892677",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "requires_python": ">=3.6",
        "size": 3015,
        "upload_time": "2022-07-23T05:03:21",
        "upload_time_iso_8601": "2022-07-23T05:03:21.091941Z",
        "url": "https://files.pythonhosted.org/packages/ab/c4/6abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b/upy_error-0.0.2-py2.py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": "",
        "digests": {
          "blake2b_256": "32af0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f",
          "md5": "bb0bba1cd339a6ff10b036fa11286609",
          "sha256": "1443e61ba8ec8c610ad761de20b3ea1604927fe876fdbb096afe043e72c7f383"
        },
        "downloads": -1,
        "filename": "upy-error-0.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "bb0bba1cd339a6ff10b036fa11286609",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": ">=3.6",
        "size": 2686,
        "upload_time": "2022-07-23T05:03:22",
        "upload_time_iso_8601": "2022-07-23T05:03:22.858984Z",
        "url": "https://files.pythonhosted.org/packages/32/af/0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f/upy-error-0.0.2.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "abc46abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b",
        "md5": "826adedaba1b854941e70d7f80892677",
        "sha256": "42ce128f084f6f6a02f53a19fc86ff8b2fc9b61f379f7343b16e7235d65916c2"
      },
      "downloads": -1,
      "filename": "upy_error-0.0.2-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "826adedaba1b854941e70d7f80892677",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "requires_python": ">=3.6",
      "size": 3015,
      "upload_time": "2022-07-23T05:03:21",
      "upload_time_iso_8601": "2022-07-23T05:03:21.091941Z",
      "url": "https://files.pythonhosted.org/packages/ab/c4/6abdc541f1478543f7aa05298ec0e75825b6e5272e87f7a75230f2913b1b/upy_error-0.0.2-py2.py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "32af0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f",
        "md5": "bb0bba1cd339a6ff10b036fa11286609",
        "sha256": "1443e61ba8ec8c610ad761de20b3ea1604927fe876fdbb096afe043e72c7f383"
      },
      "downloads": -1,
      "filename": "upy-error-0.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "bb0bba1cd339a6ff10b036fa11286609",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3.6",
      "size": 2686,
      "upload_time": "2022-07-23T05:03:22",
      "upload_time_iso_8601": "2022-07-23T05:03:22.858984Z",
      "url": "https://files.pythonhosted.org/packages/32/af/0c26dbe990fde40cfa6f32d1725d51a410eeebfa3c02236cfe83f55e2e2f/upy-error-0.0.2.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}