{
  "info": {
    "author": "",
    "author_email": "",
    "bugtrack_url": null,
    "classifiers": [
      "Framework :: Django",
      "License :: Public Domain",
      "Operating System :: OS Independent",
      "Programming Language :: Python",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: 3.6",
      "Programming Language :: Python :: 3.7"
    ],
    "description": "<!--\nhttps://pypi.org/project/readme-generator/\nhttps://pypi.org/project/python-readme-generator/\nhttps://pypi.org/project/django-readme-generator/\n-->\n\n[![](https://img.shields.io/pypi/pyversions/django-traceback.svg?longCache=True)](https://pypi.org/project/django-traceback/)\n\n#### Installation\n```bash\n$ [sudo] pip install django-traceback\n```\n\n#### Models\nmodel|`__doc__`\n-|-\n`Traceback` |Traceback(id, type, value, traceback, path, created_at)\n\n#### Functions\nfunction|`__doc__`\n-|-\n`django_traceback.utils.save_traceback(path=None)` |save a traceback\n\n#### Examples\n```python\nfrom django_traceback.utils import save_traceback\nimport requests\nfrom apps.celery import celery_app\n\n@celery_app.task\ndef task():\n    try:\n        r = requests.get('url')\n    except (requests.exceptions.ConnectionError,...):\n        save_traceback(__file__)\n        # init task again\n```\n\n<p align=\"center\">\n    <a href=\"https://pypi.org/project/django-readme-generator/\">django-readme-generator</a>\n</p>",
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/andrewp-as-is/django-traceback.py",
    "keywords": "django traceback",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "django-traceback",
    "package_url": "https://pypi.org/project/django-traceback/",
    "platform": "",
    "project_url": "https://pypi.org/project/django-traceback/",
    "project_urls": {
      "Homepage": "https://github.com/andrewp-as-is/django-traceback.py"
    },
    "release_url": "https://pypi.org/project/django-traceback/2019.10.2/",
    "requires_dist": null,
    "requires_python": "",
    "summary": "Traceback model and utils",
    "version": "2019.10.2",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 8814744,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "ee5781677596ea5731a70fcc08e1804d6db61cf98e49c4ce9f35d8b9d986b1b8",
        "md5": "9104711801a70ed5d15f69ea74d90e63",
        "sha256": "4b48669cdd35fb7cfff068016c366ac4c47cb6e13715c069cd078bb54cfeb87c"
      },
      "downloads": -1,
      "filename": "django-traceback-2019.10.2.tar.gz",
      "has_sig": false,
      "md5_digest": "9104711801a70ed5d15f69ea74d90e63",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 2302,
      "upload_time": "2019-10-02T20:51:27",
      "upload_time_iso_8601": "2019-10-02T20:51:27.774882Z",
      "url": "https://files.pythonhosted.org/packages/ee/57/81677596ea5731a70fcc08e1804d6db61cf98e49c4ce9f35d8b9d986b1b8/django-traceback-2019.10.2.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}