{
  "info": {
    "author": "Philipe",
    "author_email": "philipe.rp@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "=======\nhttp403\n=======\n\nHttp403 response from http://devwithpassion.com/felipe/manipulando-erros-http-403-permissao-negada-no-django/\n\nThis will be integrated with django-response-helpers\n\nhttps://github.com/chronossc/django-response-helpers/\nhttps://github.com/imtapps/django-response-helpers\nhttp://pypi.python.org/pypi/django-response-helpers",
    "description_content_type": null,
    "docs_url": null,
    "download_url": "UNKNOWN",
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "home_page": "https://github.com/chronossc/http403",
    "keywords": "django,exceptions,http403",
    "license": "LICENSE",
    "maintainer": null,
    "maintainer_email": null,
    "name": "django-extra-exceptions",
    "package_url": "https://pypi.org/project/django-extra-exceptions/",
    "platform": "any",
    "project_url": "https://pypi.org/project/django-extra-exceptions/",
    "project_urls": {
      "Download": "UNKNOWN",
      "Homepage": "https://github.com/chronossc/http403"
    },
    "release_url": "https://pypi.org/project/django-extra-exceptions/1.0.0/",
    "requires_dist": null,
    "requires_python": null,
    "summary": "Extra exception handling to mirror django.http.http404",
    "version": "1.0.0",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 789590,
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "blake2b_256": "0035a08cf74b7f2a6cfced49ee52a724ae2cf79bb63fd793f122e725fa26f416",
        "md5": "054eccd562631e21687586ce9db011e1",
        "sha256": "c697b22abb49b66bcb3be48327e95a107d5f1230fd1e412e44cd22278b1f2f39"
      },
      "downloads": -1,
      "filename": "django-extra-exceptions-1.0.0.tar.gz",
      "has_sig": false,
      "md5_digest": "054eccd562631e21687586ce9db011e1",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": null,
      "size": 2392,
      "upload_time": "2012-07-27T19:50:44",
      "upload_time_iso_8601": "2012-07-27T19:50:44.630403Z",
      "url": "https://files.pythonhosted.org/packages/00/35/a08cf74b7f2a6cfced49ee52a724ae2cf79bb63fd793f122e725fa26f416/django-extra-exceptions-1.0.0.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}